server:
  port: 55555

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online_exam?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 1667372479
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
