server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online-exam?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 1667372479
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
