server:
  port: 18080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yes_wms?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 133313

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
